name: flutter_application_33
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.1
  url_launcher: ^6.1.0  
  kakaomap_webview: ^0.6.2

  flutter_vlc_player: ^7.4.2  # VLC Player 패키지 (버전은 최신 버전에 맞게 설정)
  path_provider: ^2.1.4  # 파일 경로 관리 패키지
  video_player: ^2.9.2

  qr_flutter: ^4.0.0  # 최신 버전 확인 후 사용
  
  http: ^0.13.3
  provider: ^6.1.2

  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/warehouse1.jpg
    - assets/ShareWare_logo.png
    - assets/.env
